Add disk space cleanup step in workflow
Added a step to free disk space before running jobs.

diff --git a/.github/workflows/test_descwl_shear_sims.yaml b/.github/workflows/test_descwl_shear_sims.yaml
--- a/.github/workflows/test_descwl_shear_sims.yaml
+++ b/.github/workflows/test_descwl_shear_sims.yaml
@@ -16,6 +16,30 @@ jobs:
     runs-on: "ubuntu-latest"
 
     steps:
+      - name: free disk space
+        run: |
+          sudo mkdir -p /opt/empty_dir || true
+          for d in \
+          /opt/ghc \
+          /opt/hostedtoolcache \
+          /usr/lib/jvm \
+          /usr/local/.ghcup \
+          /usr/local/lib/android \
+          /usr/local/share/powershell \
+          /usr/share/dotnet \
+          /usr/share/swift \
+          ; do
+            sudo rsync --stats -a --delete /opt/empty_dir/ $d || true
+          done
+          # dpkg does not fail if the package is not installed
+          sudo dpkg --remove -y -f firefox \
+                                  google-chrome-stable \
+                                  microsoft-edge-stable
+          sudo apt-get autoremove -y >& /dev/null
+          sudo apt-get autoclean -y >& /dev/null
+          sudo docker image prune --all --force
+          df -h
+
       - uses: actions/checkout@v2
 
       - uses: conda-incubator/setup-miniconda@v2
